version: '3'
networks:
  default:
    name: rhub-development
services:
  rhub-app:
    image: quay.io/resource-hub-dev/rhub-app:${RHUB_FRONTEND_IMAGE_TAG:-dev}
    volumes:
      - /opt/app-root/src/node_modules/
      - .:/opt/app-root/src:delegated
    environment:
      RHUB_API_URL: ${RHUB_API_URL:-http://localhost:8081/v0/}
      RHUB_KEYCLOAK_URL: ${RHUB_KEYCLOAK_URL:-http://localhost:8080/auth/}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-rhub}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT:-rhub-app}
      # don't pollute /opt/app-root/src with home crap
      HOME: /opt/app-root/home
      NPM_CONFIG_PREFIX: /opt/app-root/home/.npm-global
    ports:
      - "3000:3000"
