version: '3'
networks:
  default:
    name: rhub-development
services:
  app:
    image: registry.access.redhat.com/ubi8/nodejs-14
    volumes:
      - .:/opt/app-root/src:delegated
    environment:
      RHUB_API_URL: http://localhost:8081
      # don't pollute /opt/app-root/src with home crap
      HOME: /opt/app-root/home
      NPM_CONFIG_PREFIX: /opt/app-root/home/.npm-global
    ports:
      - 8080:8080
    # prettier-ignore
    command: ["./node_modules/.bin/webpack", "serve", "--mode", "development", "--host", "0.0.0.0"]
