version: '3'
networks:
  default:
    name: rhub-development
services:
  app:
    build:
      context: .
      target: base
    volumes:
      - .:/opt/rhub-app:delegated
    environment:
      RHUB_API_URL: http://localhost:8081
    ports:
      - 8080:8080
    # prettier-ignore
    command: ["./node_modules/.bin/webpack", "serve", "--mode", "development", "--host", "0.0.0.0"]
