FROM node:18.12.1
# Keep the cache for node packages...
WORKDIR /opt/app-root/src
COPY package*.json ./
RUN npm install

COPY . .
CMD ["npm", "run", "start"]

HEALTHCHECK --interval=10s --retries=5 --timeout=5s CMD ["curl", "-f", "http://localhost:3000"]
