version: '3'
networks:
  default:
    name: rhub-development
services:
  app:
    image: node:14
    volumes:
      - .:/rhub-app:delegated
    ports:
      - 8080:8080
    working_dir: /rhub-app
    command: ["./node_modules/.bin/webpack", "serve", "--mode", "development", "--host", "0.0.0.0"]
