#!/usr/bin/env sh

set -ex

envsubst ' \
	$RHUB_API_URL \
	$RHUB_KEYCLOAK_URL \
	$KEYCLOAK_REALM \
	$KEYCLOAK_CLIENT \
	$RHUB_BROKER_HOST \
	$RHUB_BROKER_USERNAME \
	$RHUB_BROKER_PASSWORD \
	' \
	< /opt/app-root/src/index.template.html > /opt/app-root/src/index.html

exec "$@"
