#!/usr/bin/env sh

set -ex

envsubst ' \
	$RHUB_API_URL \
	$RHUB_KEYCLOAK_URL \
	$KEYCLOAK_REALM \
	$KEYCLOAK_CLIENT \
	' \
	< /opt/app-root/src/index.template.html > /opt/app-root/src/index.html

exec "$@"
